---
title: "Rebecca N Assignment 8"
output: html_notebook
author: "Rebecca Neal"
date: "3 April 2020"
version: "2.0 cleaning up Git Kraken"
---

This is for EDRM 718 Assignment 8 in which we will practice writing scripts and
use the tidy verse package

Load the package
```{r}
library(tidyverse)
```

This is a function to reverse score identified columns and create a total score
```{r include=FALSE}
Likert_Total <- function(x,y,z){
  Reversed <- abs(x[,c(z)]-y)
  Non_Reversed_Columns <- x[,-z]
  Properly_Scored_Data_Frame <- cbind(Non_Reversed_Columns,Reversed)
  CC <- rowSums(Properly_Scored_Data_Frame)
  Total_Data_Frame <- cbind(Properly_Scored_Data_Frame,CC)
  write.csv("Total_Data_Frame", file = "Total Data Frame.csv", row.names = FALSE)
  return(Total_Data_Frame)
}
```

Load in data
```{r}
HD_ugly <- read_csv("Howard's Data.csv")
HD <- HD_ugly[-1]
HD
```

This is practicing that script with Howard's data
```{r}
CTR <- c(3,5,7)
Howard_Data <- Likert_Total(HD, 8, CTR)
Howard_Data
```


Load ggplot package
```{r}
library(ggplot2)
```

Read in hsb2 data
```{r include=FALSE}
hsb2 <- read_csv("hsb2.csv")
```

Question 3 - Math and Science scores by gender
```{r}
ggplot(data = hsb2) +
  geom_point(mapping = aes(x = math, y = science, color = female))
```




